apiVersion: v1
kind: Service
metadata:
  name: facial-recognition-backend
spec:
  selector:
    app: facial-recognition
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: facial-recognition-frontend
spec:
  selector:
    app: facial-recognition
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
